ccflags-y += -Werror

obj-$(CONFIG_VSERVICES_PROTOCOL_ETHERNET_SERVER) += vservices_protocol_ethernet_server.o
vservices_protocol_ethernet_server-objs = server.o

obj-$(CONFIG_VSERVICES_PROTOCOL_ETHERNET_CLIENT) += vservices_protocol_ethernet_client.o
vservices_protocol_ethernet_client-objs = client.o
